repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  # Stop commits to master
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]  

  - repo: local
    hooks:
  
      - id: lint
        name: lint
        language: system  # Running on the local system
        stages: [commit, push]
        verbose: true
        entry: make lint
        types: [file, python]  # Only triggered if python files are changed in the commit
        pass_filenames: false

